const name = "TRANSACTIONS";

export const FETCH_TRANSACTIONS_ETH = `${name}/FETCH_TRANSACTIONS_ETH`;
export const FETCH_TRANSACTIONS_ETH_START = `${FETCH_TRANSACTIONS_ETH}/START`;
export const FETCH_TRANSACTIONS_ETH_END = `${FETCH_TRANSACTIONS_ETH}/END`;
export const FETCH_TRANSACTIONS_ETH_FAILURE = `${FETCH_TRANSACTIONS_ETH}/FAILURE`;
export const FETCH_TRANSACTIONS_ETH_SUCCESS = `${FETCH_TRANSACTIONS_ETH}/SUCCESS`;

export const FETCH_TRANSACTIONS_ERC20 = `${name}/FETCH_TRANSACTIONS_ERC20`;
export const FETCH_TRANSACTIONS_ERC20_START = `${FETCH_TRANSACTIONS_ERC20}/START`;
export const FETCH_TRANSACTIONS_ERC20_END = `${FETCH_TRANSACTIONS_ERC20}/END`;
export const FETCH_TRANSACTIONS_ERC20_FAILURE = `${FETCH_TRANSACTIONS_ERC20}/FAILURE`;
export const FETCH_TRANSACTIONS_ERC20_SUCCESS = `${FETCH_TRANSACTIONS_ERC20}/SUCCESS`;

export const CREATE_TRANSACTION = `${name}/CREATE_TRANSACTION`;
export const CREATE_TRANSACTION_START = `${CREATE_TRANSACTION}/START`;
export const CREATE_TRANSACTION_END = `${CREATE_TRANSACTION}/END`;
export const CREATE_TRANSACTION_FAILURE = `${CREATE_TRANSACTION}/FAILURE`;
export const CREATE_TRANSACTION_SUCCESS = `${CREATE_TRANSACTION}/SUCCESS`;

export const FETCH_TRANSACTION = `${name}/FETCH_TRANSACTION`;
export const FETCH_TRANSACTION_START = `${FETCH_TRANSACTION}/START`;
export const FETCH_TRANSACTION_END = `${FETCH_TRANSACTION}/END`;
export const FETCH_TRANSACTION_FAILURE = `${FETCH_TRANSACTION}/FAILURE`;
export const FETCH_TRANSACTION_SUCCESS = `${FETCH_TRANSACTION}/SUCCESS`;

export const RESET = `${name}/RESET`;