const name = "WALLET";

export const FETCH_WALLET_BALANCES = `${name}/FETCH_WALLET_BALANCES`;
export const FETCH_WALLET_BALANCES_START = `${FETCH_WALLET_BALANCES}/START`;
export const FETCH_WALLET_BALANCES_END = `${FETCH_WALLET_BALANCES}/END`;
export const FETCH_WALLET_BALANCES_FAILURE = `${FETCH_WALLET_BALANCES}/FAILURE`;
export const FETCH_WALLET_BALANCES_SUCCESS = `${FETCH_WALLET_BALANCES}/SUCCESS`;

export const SET_WALLET_ADDRESS = `${name}/SET_WALLET_ADDRESS`;

export const UNLOCK = `${name}/UNLOCK`;

export const RESET = `${name}/RESET`;